runner:
  golangci:
    cmd: golangci-lint run ./...
    errorformat:
      - '%E%f:%l:%c: %m'
      - '%E%f:%l: %m'
      - '%C%.%#'
  wraperr:
    cmd: wraperr ./...
    errorformat:
      - "%f:%l:%c:%m"
