version: 2.1

orbs:
  go-module: timakin/go-module@0.3.0
  go-crossbuild: izumin5210/go-crossbuild@0.1.1
  github-release: izumin5210/github-release@0.1.1
  homebrew: izumin5210/homebrew@0.1.1
  protobuf: izumin5210/protobuf@0.1.0
  inline: izumin5210/inline@0.1.0

executors:
  golang:
    parameters:
      version:
        type: string
        default: '1.12'
    docker:
      - image: circleci/golang:<< parameters.version >>
    environment:
      - GO111MODULE: "on"

aliases:
  go1.11: &go-1-11
    executor:
      name: golang
      version: '1.11'
  go1.12: &go-1-12
    executor:
      name: golang
      version: '1.12'
  filter-all: &filter-all
    filters:
      tags:
        only: /.*/
  filter-release: &filter-release
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^v\d+\.\d+\.\d+$/

workflows:
  build_and_release:
    jobs:
      - go-module/download: &setup-base
          <<: *filter-all
          <<: *go-1-12
          name: 'setup-1.12'
          persist-to-workspace: true
          vendoring: true

      - go-module/download:
          <<: *setup-base
          <<: *go-1-11
          name: 'setup-1.11'

      - inline/steps:
          <<: *go-1-12
          name: 'lint'
          context: reviewdog
          steps:
            - run: make lint
          requires:
            - setup-1.12

      - inline/steps:
          <<: *go-1-12
          name: 'test-1.12'
          steps:
            - run: make cover
            - run: bash <(curl -s https://codecov.io/bash)
          requires:
            - setup-1.12

      - inline/steps:
          <<: *go-1-11
          name: 'test-1.11'
          steps:
            - run: make test
          requires:
            - setup-1.11

      - inline/steps:
          <<: *go-1-12
          name: 'test-e2e-1.12'
          steps:
            - protobuf/install
            - run: make test-e2e TARGET_REVISION=$CIRCLE_SHA1
          requires:
            - setup-1.12

      - inline/steps:
          <<: *go-1-11
          name: 'test-e2e-1.11'
          steps:
            - protobuf/install
            - run: make test-e2e TARGET_REVISION=$CIRCLE_SHA1
          requires:
            - setup-1.11

      - go-crossbuild/build:
          <<: *filter-all
          <<: *go-1-12
          app-name: grapi
          packages: ./cmd/grapi
          ldflags: "-X main.revision=$(git describe --always) -X main.buildDate=$(date +'%Y-%m-%dT%H:%M:%SZ')"
          requires:
            - setup-1.12

      - github-release/create:
          <<: *filter-release
          context: tool-releasing
          requires:
            - test-1.12
            - test-1.11
            - test-e2e-1.12
            - test-e2e-1.11
            - go-crossbuild/build

      - homebrew/update:
          <<: *filter-release
          context: tool-releasing
          requires:
            - github-release/create
