name: CI

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    name: test with go${{ matrix.go }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: izumin5210/actions-go-crossbuild@master
        with:
          name: 'clig'
          package: './cmd/clig'
      - uses: izumin5210/actions-github-releases@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
